### PR TITLE
Fully functioning webpage. Still need saving feature to be added.

### PR DESCRIPTION
**Pull request by AbdelrahmanAhmed605**
- Webpage contains overall layout from wireframe
- Fetch requests to receive articles from Gnews and display articles on the carousel and headline section
- Fetch requests to play audio using VoiceRSS api to read out descriptions of displayed articles

### CODE REVIEW

**Review by MadDonald — APPROVED** [review]
Looks good to me, thanks!

**Comment by gabetuason** [comment]
Reviewed the code and it is functional.

**Review by MadDonald — APPROVED** [review]
Looks good to me

**Review by gabetuason — APPROVED** [review]
The webpage is functioning as it should. Carousel is pulling the articles and the bottom section cards are also doing the same. The voice is working and pausing when need be. Navigation bar leads to the correct HTML and the buttons are functional.

**Pull request merged**
